### ISSUE TITLE
Use of Pyev3

### ISSUE THREAD

**Issue by hlmhv** [EduardoNigro/pyev3#1]
Dear Eduardo,

I thank you for your Pyev3 wich I installed yesterday: nice, usefull, very simple (on Thonny beause VC is so complicated..), without any trouble.. :-)
Just a small question: do you plan to extend it? For example, I 'm looking for a way to get voltage & actual current of the Mindstorm and the read only variable "batterylevel" doesn't give these..

But first of all  i'm very happy to work with Pyev3!

Kind regards,

Henri Maquoi,
Belgium

**Comment by EduardoNigro** [comment]
Thank you for your comment, Henri!
I do not plan on extending it. I should mention that I tried to extract those two parameters but wasn't able to do so.

PS. You should give VS Code a second try ;-)
